import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from '@/app/components/Footer';
import { headers } from "next/headers";
import DashboardNav from "./components/DashboardNav";
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300','400','500','600','700'],
  variable: '--font-poppins',   
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  
  const path = headersList.get("x-current-path")
  

  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {
          path === "/dashboard"? 
          <DashboardNav/>: <Navbar/>
        }
        {children}
        <Footer/>
      </body>
    </html>
  );
}
